/* ==============================================================
   levels.js -- Auto-generated by extract-vocab.py
   DO NOT EDIT -- regenerate with: python3 scripts/extract-vocab.py
   ============================================================== */

var LEVELS = [
];
