#!/usr/bin/env python3
"""
extract-vocab.py -- Extract vocabulary from .tex files.

Reads data/sources.json, parses .tex files, generates js/levels.js.

Usage:
    python3 scripts/extract-vocab.py
"""

import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
SOURCES_FILE = os.path.join(PROJECT_ROOT, "data", "sources.json")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "js", "levels.js")

MAX_WORDS_PER_LEVEL = 10
MIN_WORDS_PER_LEVEL = 4

_BS = re.escape(chr(92))

TABLE_RE = re.compile(
    _BS + "begin" + r"\{VocabTable\}\{([^}]*)\}\{([^}]*)\}(.*?)" + _BS + "end" + r"\{VocabTable\}",
    re.DOTALL,
)
ROW_RE = re.compile(
    _BS + "VocabRow" + r"\{([^}]*)\}\{([^}]*)\}\{([^}]*)\}\{([^}]*)\}"
)
TEXTCMD_RE = re.compile(
    _BS + "text(?:it|bf|rm|sf)" + r"\{([^}]*)\}"
)


def parse_tex_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    groups = []
    for table_match in TABLE_RE.finditer(content):
        en_title = table_match.group(1).strip()
        zh_title = table_match.group(2).strip()
        body = table_match.group(3)

        words = []
        for row_match in ROW_RE.finditer(body):
            english = row_match.group(1).strip()
            chinese = row_match.group(2).strip()
            english = clean_latex(english)
            words.append({"word": english, "def": chinese})

        if words:
            groups.append(
                {"en_title": en_title, "zh_title": zh_title, "words": words}
            )

    return groups


def clean_latex(text):
    """Remove LaTeX commands from text."""
    text = re.sub(r"[$]([^$]*)[$]", r"\1", text)
    text = TEXTCMD_RE.sub(r"\1", text)
    text = re.sub(_BS + r"[,;!]", "", text)
    text = re.sub(_BS + "ldots", "...", text)
    return text.strip()


def split_group(group, max_size=MAX_WORDS_PER_LEVEL):
    words = group["words"]
    if len(words) <= max_size:
        return [group]

    subgroups = []
    for i in range(0, len(words), max_size):
        chunk = words[i : i + max_size]
        if len(chunk) < MIN_WORDS_PER_LEVEL and subgroups:
            subgroups[-1]["words"].extend(chunk)
        else:
            suffix = f" ({i // max_size + 1})" if len(words) > max_size else ""
            subgroups.append({
                "en_title": group["en_title"] + suffix,
                "zh_title": group["zh_title"] + suffix,
                "words": chunk,
            })

    return subgroups


def calc_timer(word_count):
    if word_count <= 6: return 90
    elif word_count <= 8: return 80
    else: return 70


def calc_combo_bonus(word_count):
    if word_count <= 6: return 3
    elif word_count <= 8: return 3
    else: return 2


def generate_levels_js(all_levels):
    lines = [
        "/* ==============================================================",
        "   levels.js -- Auto-generated by extract-vocab.py",
        "   DO NOT EDIT MANUALLY -- regenerate with: python3 scripts/extract-vocab.py",
        "   ============================================================== */",
        "",
        "var LEVELS = [",
    ]

    for i, level in enumerate(all_levels):
        title = level["title"]
        words = level["words"]
        timer = calc_timer(len(words))
        combo = calc_combo_bonus(len(words))

        lines.append("  {")
        lines.append(f'    title: {json.dumps(title, ensure_ascii=False)},')
        lines.append(f"    timer: {timer},")
        lines.append(f"    comboBonus: {combo},")
        lines.append("    vocabulary: [")

        for j, w in enumerate(words):
            wid = j + 1
            word_json = json.dumps(w["word"], ensure_ascii=False)
            def_json = json.dumps(w["def"], ensure_ascii=False)
            comma = "," if j < len(words) - 1 else ""
            lines.append(
                f'      {{ id: {wid}, type: "word", content: {word_json} }}, '
                f'{{ id: {wid}, type: "def", content: {def_json} }}{comma}'
            )

        lines.append("    ]")
        comma = "," if i < len(all_levels) - 1 else ""
        lines.append("  }" + comma)

    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    if not os.path.exists(SOURCES_FILE):
        print(f"Error: {SOURCES_FILE} not found", file=sys.stderr)
        sys.exit(1)

    with open(SOURCES_FILE, "r", encoding="utf-8") as f:
        sources = json.load(f)

    all_levels = []
    total_words = 0

    for category, files in sources.items():
        print(f"\n=== {category} ===")
        for entry in files:
            filepath = os.path.normpath(
                os.path.join(PROJECT_ROOT, entry["file"])
            )
            prefix = entry["prefix"]

            if not os.path.exists(filepath):
                print(f"  WARNING: {filepath} not found, skipping")
                continue

            groups = parse_tex_file(filepath)
            print(f"  {prefix}: {len(groups)} groups")

            for group in groups:
                subgroups = split_group(group)
                for sg in subgroups:
                    title = sg['zh_title']
                    word_count = len(sg['words'])
                    total_words += word_count
                    all_levels.append({'title': title, 'words': sg['words']})
                    print(f"    -> {title} ({word_count} words)")

    js_content = generate_levels_js(all_levels)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"\n{'=' * 50}")
    print(f"Generated {OUTPUT_FILE}")
    print(f"  Levels: {len(all_levels)}")
    print(f"  Total words: {total_words}")
    print(f"{'=' * 50}")


if __name__ == "__main__":
    main()
