#!/usr/bin/env python3
"""extract-vocab.py -- Extract vocabulary from .tex files into js/levels.js"""

import json, os, re, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
SOURCES_FILE = os.path.join(PROJECT_ROOT, "data", "sources.json")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "js", "levels.js")
MAX_PER_LEVEL = 10
MIN_PER_LEVEL = 4

# Regex-safe literal backslash for Python 3.13+
_B = re.escape(chr(92))

TABLE_RE = re.compile(
    _B + r"begin\{VocabTable\}\{([^{}]*)\}\{([^{}]*)\}(.*?)" + _B + r"end\{VocabTable\}",
    re.DOTALL)
ROW_RE = re.compile(
    _B + r"VocabRow\{([^{}]*)\}\{([^{}]*)\}\{([^{}]*)\}\{([^{}]*)\}")
TXTCMD_RE = re.compile(
    _B + r"text(?:it|bf|rm|sf)\{([^{}]*)\}")


def parse_tex(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    groups = []
    for tm in TABLE_RE.finditer(content):
        en_title = tm.group(1).strip()
        zh_title = tm.group(2).strip()
        words = []
        for rm in ROW_RE.finditer(tm.group(3)):
            words.append({"word": clean(rm.group(1).strip()), "def": rm.group(2).strip()})
        if words:
            groups.append({"en": en_title, "zh": zh_title, "words": words})
    return groups


def clean(text):
    text = re.sub(r"[$]([^$]*)[$]", r"\1", text)
    text = TXTCMD_RE.sub(r"\1", text)
    text = re.sub(_B + r"[,;!]", "", text)
    text = re.sub(_B + "ldots", "...", text)
    return text.strip()


def split_group(g):
    words = g["words"]
    if len(words) <= MAX_PER_LEVEL:
        return [g]
    subs = []
    for i in range(0, len(words), MAX_PER_LEVEL):
        chunk = words[i:i + MAX_PER_LEVEL]
        if len(chunk) < MIN_PER_LEVEL and subs:
            subs[-1]["words"].extend(chunk)
        else:
            suffix = f" ({i // MAX_PER_LEVEL + 1})" if len(words) > MAX_PER_LEVEL else ""
            subs.append({"en": g["en"] + suffix, "zh": g["zh"] + suffix, "words": chunk})
    return subs


def calc_timer(n):
    return 90 if n <= 6 else (80 if n <= 8 else 70)


def calc_combo(n):
    return 3 if n <= 8 else 2


def gen_js(levels):
    out = [
        "/* ==============================================================",
        "   levels.js -- Auto-generated by extract-vocab.py",
        "   DO NOT EDIT -- regenerate with: python3 scripts/extract-vocab.py",
        "   ============================================================== */",
        "",
        "var LEVELS = [",
    ]
    for i, lv in enumerate(levels):
        t, w = lv["title"], lv["words"]
        out.append("  {")
        out.append(f'    title: {json.dumps(t, ensure_ascii=False)},')
        out.append(f"    timer: {calc_timer(len(w))},")
        out.append(f"    comboBonus: {calc_combo(len(w))},")
        out.append("    vocabulary: [")
        for j, wd in enumerate(w):
            wid = j + 1
            wj = json.dumps(wd["word"], ensure_ascii=False)
            dj = json.dumps(wd["def"], ensure_ascii=False)
            c = "," if j < len(w) - 1 else ""
            out.append(f'      {{ id: {wid}, type: "word", content: {wj} }}, {{ id: {wid}, type: "def", content: {dj} }}{c}')
        out.append("    ]")
        out.append("  }" + ("," if i < len(levels) - 1 else ""))
    out.append("];")
    out.append("")
    return chr(10).join(out)


def main():
    with open(SOURCES_FILE, "r", encoding="utf-8") as f:
        sources = json.load(f)
    all_levels, total = [], 0
    for cat, files in sources.items():
        print(f"\n=== {cat} ===")
        for entry in files:
            fp = os.path.normpath(os.path.join(PROJECT_ROOT, entry["file"]))
            if not os.path.exists(fp):
                print(f"  SKIP: {fp}")
                continue
            groups = parse_tex(fp)
            print(f"  {entry['prefix']}: {len(groups)} groups")
            for g in groups:
                for sg in split_group(g):
                    n = len(sg["words"])
                    total += n
                    all_levels.append({"title": sg["zh"], "words": sg["words"]})
                    print(f"    -> {sg['zh']} ({n} words)")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(gen_js(all_levels))
    print(f"\nDone: {len(all_levels)} levels, {total} words => {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
